### ISSUE TITLE
timeseries 元数据tag、attribute目前不支持修改、删除、新增

### ISSUE THREAD

**Issue by juice411** [apache/incubator-iotdb#1093]
create timeseries root.turbine.d1.s1(temprature) with datatype=FLOAT, encoding=RLE, compression=SNAPPY tags(tag1=v1, tag2=v2) attributes(attr1=v1, attr2=v2)
目前支持在新建timeseries 的时候可以添加tag等标签信息，但一旦实施人员疏忽或需求变化，前期添加的tag信息就没法更新，除非删除timeseries重新建，这样涉及到已有数据是不能删除的，因此很麻烦，需要类似如下的功能：
alter timeseries root.turbine.d1.s1 change tag1 newV1
alter timeseries root.turbine.d1.s1 add tag3 v3
alter timeseries root.turbine.d1.s1 drop tag2

这样就可以方便的管理这些信息而不用删除数据

**Comment by qiaojialin** [comment]
https://issues.apache.org/jira/browse/IOTDB-617

http://iotdb.apache.org/UserGuide/Master/5-Operation%20Manual/1-DDL%20Data%20Definition%20Language.html
