### ISSUE TITLE
last 查询中如果用了别名返回结果中丢失别名信息

### ISSUE THREAD

**Issue by juice411** [apache/incubator-iotdb#1144]
![图片](https://user-images.githubusercontent.com/10968514/80854608-0b2bd500-8c6c-11ea-88c5-8bd9df4e8b6c.png)
如图所示，select last exName0000009 from root.DDM.XDB，返回结果中却是root.DDM.XDB.tag0000009，应该保持别名信息

**Comment by qiaojialin** [comment]
https://github.com/apache/incubator-iotdb/pull/1183
原始数据查询和Last查询已支持
