### ISSUE TITLE
client工具查询异常

### ISSUE THREAD

**Issue by FoxNo2** [apache/incubator-iotdb#1197]
**0.10.0-SNAPSHOT版本**
client工具先执行错误SQL再执行正确SQL后,返回的数据异常.
步骤如下:

1. 使用JDBC Example代码向root.demo.s0到root.demo.s29,共30个时间序列,各写入1000000个数据.

2. 使用client工具连接到server.

3. 执行 select count(s0) from root.demo,结果为1000000,此结果正确.

4. 连续输入并执行错误的SQL语句:

> - select count(s0,s1) from root.demo
> (Msg: Index 0 out of bounds for length 0)
>  - select count(*) from root.demo.s0
>(Msg: 401: line 1:15 missing ')' at ',')

5. 执行 select count(s0) from root.demo,此时返回的结果为:Empty set.此结果错误.

6. 执行 select count(s0) from root.demo,结果为1000000,结果又变为正确.

此现象是否存在异常?

**Comment by FoxNo2** [comment]
IoTDB> select count(s0) from root.demo

> +-------------------+
> |count(root.demo.s0)|
> +-------------------+
> |            1000000|
> +-------------------+
> Total line number = 1
> It costs 0.054s

IoTDB> select count(*) from root.demo.s0
> Msg: Index 0 out of bounds for length 0

IoTDB> select count(s0,s1) from root.demo

> Msg: 401: line 1:15 missing ')' at ','

IoTDB> select count(s0) from root.demo

> +-------------------+
> |count(root.demo.s0)|
> +-------------------+
> +-------------------+
> Empty set.
> It costs 0.051s

IoTDB> select count(s0) from root.demo

> +-------------------+
> |count(root.demo.s0)|
> +-------------------+
> |            1000000|
> +-------------------+
> Total line number = 1
> It costs 0.056s

**Comment by qiaojialin** [comment]
感谢反馈，是异常，需要改进一下

**Comment by qiaojialin** [comment]
https://github.com/apache/incubator-iotdb/pull/1199
