### ISSUE TITLE
数据库需支持按时间自定义排序规则，降序或者升序(Support `ORDER BY TIME DESC`)

### ISSUE THREAD

**Issue by chenping817** [apache/incubator-iotdb#1225]
目前某些业务场景是需要查询时序库的历史数据，但是客户往往只关注最近几天的数据，可是SQL却不支持时间的倒序查询，如关系库的order by time desc。

**Comment by zhangJiangKai** [comment]
同问后续是否增加排序。以及按数值内容排序的功能呢？

**Comment by qiaojialin** [comment]
> 同问后续是否增加排序。以及按数值内容排序的功能呢？

会在一两个月内增加按时间戳降序排列的功能，按数值内容排列的功能会之后再考虑增加
