### ISSUE TITLE
请问,这个报错是为什么(group by Statement format is not right)

### ISSUE THREAD

**Issue by liwh1111** [apache/incubator-iotdb#1236]
![image](https://user-images.githubusercontent.com/63097736/82543659-7c351d00-9b86-11ea-9840-2377b1a81386.png)

**Comment by qiaojialin** [comment]
您好，这个group by 语法应该是 0.10 版本的。

0.9版本的 group by 语法是这种：

select AVG(s1) from root.sg1.d1 where time > xxx and time < xx group by (1m,[2017-11-01T00:00:00, 2017-11-07T23:00:00])

用户手册里 in progress 是最新开发分支的，0.9.x 是0.9 的。
![image](https://user-images.githubusercontent.com/7240743/82552031-f0c28880-9b93-11ea-8428-30e47e52e3f2.png)

http://iotdb.apache.org/UserGuide/V0.9.x/5-Operation%20Manual/2-DML%20Data%20Manipulation%20Language.html#down-frequency-aggregate-query

**Comment by liwh1111** [comment]
好的,谢谢,换成0.9.3版本好了
