### ISSUE TITLE
Msg: 500: all cached chunks should be consumed first

### ISSUE THREAD

**Issue by aiping312** [apache/incubator-iotdb#1261]
你好请问，这个是因为什么原因导致的？

IoTDB> SELECT max_time(5452) FROM root.lin.l1.18_0 where time < 1590388748190 and time > 1590016639981  GROUP BY([1590016639981, 1590088748190), 1m)
Msg: 500: all cached chunks should be consumed first

**Comment by qiaojialin** [comment]
这是一个查询的bug，可以拉一下现在的 master 分支重新测试一下，应该修复了

**Comment by aiping312** [comment]
好的 谢谢
