### ISSUE TITLE
root密码修改不成功

### ISSUE THREAD

**Issue by liujiling1** [apache/incubator-iotdb#1279]
ALTER USER root SET PASSWORD '123456';
修改密码报错；

ALTER USER testSET PASSWORD '123456';
其他用户就能修改成功，为啥子？？

**Comment by qiaojialin** [comment]
这个 bug 在 master 分支 0.10.0-SNAPSHOT 修复了，如果其他分支需要改，可以应用一下这个 PR
https://github.com/apache/incubator-iotdb/pull/750
