### ISSUE TITLE
start-server.bat quits unexpectedly in Windows

### ISSUE THREAD

**Issue by Ring-k** [apache/incubator-iotdb#1334]
**The Problem**
After compilation, double clicking the "start-server.bat" results in quitting unexpectedly. 

 **Possible solution**
  - Windows fails to execute when the path of "lib" is too long. In this case, copy the whole folder "iotdb-server-0.10.0-SNAPSHOT" to wherever the path is shorter, and then try executing the "start-server.bat" again.

**Comment by qiaojialin** [comment]
Make sure the path does not contain blank, e.g., "Program Files"

**Comment by jixuan1989** [comment]
#1377  has fixed the too long path issue for WinOS
