### ISSUE TITLE
SQL执行时间怎样优化到毫秒级别？还是说根本就不可能？

### ISSUE THREAD

**Issue by kqkdChen** [apache/incubator-iotdb#1425]
data count: **18999994** total
SQL: **select * from root.position where time > 1559179819000 limit 10**
执行上述sql：
shell client显示花费时间： **6.171S**
![image](https://user-images.githubusercontent.com/41674301/85938068-3f560600-b93c-11ea-8d32-191462885398.png)

IOTDB Metrics Server：**0-7ms??????????**
![image](https://user-images.githubusercontent.com/41674301/85938110-8217de00-b93c-11ea-9b86-6abbabbf30b1.png)

为什么两者差别如此之大？
我还尝试使用jdbc api，时间花费在5s，我以为查询会很强，没想到这么弱，感觉比不上HBase...

这是你们的产品介绍，我不知道是否是我的用法有问题，查询根本做不到毫秒级别，超过300W数据就已经是秒级别了，官网的文档也不详细，基本的性能调优我都没有找到。
![image](https://user-images.githubusercontent.com/41674301/85938135-cefbb480-b93c-11ea-8b00-8d58f4527686.png)

求解惑，还有尽快完善文档吧，连集群模式都没有，生产谁敢用...

**Comment by kqkdChen** [comment]
CPU      Cores:  8 Total, 29% CPU Ratio
JVM Memory:  1969 1969 1295 (Max/Total/Free)MB
Host Memory: 16 GB Total, 5.0 GB Used

18999994条数据 count 下竟然将近9秒。
![image](https://user-images.githubusercontent.com/41674301/85938217-ca83cb80-b93d-11ea-88b8-a839a7801c10.png)

**Comment by jixuan1989** [comment]
> select * from root.position where time > 1559179819000 limit 10
如果limit10的话，不应该6s吧？ @qiaojialin 

> 18999994条数据 count 下竟然将近9秒。
请问这个有乱序数据吗？ （data/data/unsequence 目录是否未空？）
另外，目前主分支还没合并PISA索引，#1439

**Comment by qiaojialin** [comment]
了解了一下，有两个原因。
第一个是数据写入是并行写一个时间段的数据，导致磁盘上相互重叠的乱序数据块非常多，查一个点也需要读所有重叠的数据块做 merge，乱序也会影响聚合查询，本来可以读预计算的值，有乱序就需要读原始数据。

第二个是我们一个默认参数设置的不太好，avg_series_point_number_threshold 设置的比较，之前默认是10000，序列少、序列比较长的时候，数据块就比较小，对查询不友好。现在改成了 30万。

客户端注意一下写入模式，只要顺序写就没问题了。乱序可以有，但是太多会影响性能。
