### ISSUE TITLE
"StorageEngineFailureException" after reboot IOTDB-0.9.3

### ISSUE THREAD

**Issue by kohlersDagger** [apache/incubator-iotdb#1444]
**Describe the bug**
IOTDB重启后无法登录，抛出StorageEngineFailureException

**To Reproduce**
1. 凌晨3点左右IOTDB报警 , GC overhead limit exceeded
2. 7点丢失与IOTDB的心跳
3. 10点左右试图CLI登录IOTDB失败，遂重启
4. IOTDB重启后依旧无法登录，抛出StorageEngineFailureException

**Screenshots**
![2020_1](https://user-images.githubusercontent.com/49938137/86209216-a4ac3000-bba4-11ea-9353-22b513540ca1.png)

**Desktop**
 - OS: windows server
 - Version: 0.9.3

**Comment by qiaojialin** [comment]
Hi, this is due to we do not catch all exception when redo WAL. This is fixd in rel/0.9 (0.9.4-SNAOSHOT) and later versions. You can download rel/0.9 branch and package the server.
