### ISSUE TITLE
缺少授权?授权读写后无法使用last

### ISSUE THREAD

**Issue by zhangJiangKai** [apache/incubator-iotdb#1571]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/33944793/88616345-89aade00-d0c6-11ea-9995-566cdc916a24.png)
![image](https://user-images.githubusercontent.com/33944793/88616355-8e6f9200-d0c6-11ea-8666-2fa63e50299c.png)

**Describe the solution you'd like**
如何进行last授权

**Comment by samperson1997** [comment]
感谢反馈，此问题将在 PR #1587 合并后在master分支修复 : )

Thanks for your feedback. This issue will be fixed after PR #1587 is merged.
