### ISSUE TITLE
TsFile同步工具如何将数据文件同步到HDFS文件系统中去？

### ISSUE THREAD

**Issue by ppyu** [apache/incubator-iotdb#1579]
在IoTDB的官方文档 **概述-架构** 章节中有如下一段话：
对于写入到IoTDB的数据以及本地的TsFile文件，可以通过同步工具TsFileSync**将数据文件同步到HDFS**上，进而实现在Hadoop或Spark的数据处理平台上的诸如异常检测、机器学习等数据处理任务。

但文档中对同步工具的介绍中，只表明同步工具只能将tsfile从一个IoTDB同步到另一个IoTDB中，没有描述TsFileSync可以**将数据文件同步到HDFS**上。
请问这个功能能实现吗？

**Comment by samperson1997** [comment]
您好！很抱歉之前在修改文档中的图片时，忽略了文字中的问题。目前**不**支持使用TsFileSync可以将数据文件同步到HDFS上，以同步工具的介绍为准，感谢指证！
文档的文字描述将会在 PR #1586 合并后修复。

Hi, sorry for the incorrect description. We do **not** support using TsFileSync tool to synchronize the TsFile to the HDFS currently, and please subject to the introduction of synchronization tools. Thanks for your correction!
This issue will be fixed after merging PR #1586 .
