### ISSUE TITLE
IoTDB是否支持k8s部署 (Whether support K8S)

### ISSUE THREAD

**Issue by ATM006** [apache/incubator-iotdb#1614]
我想使用k8s YAML文件部署

**Comment by kqkdChen** [comment]
你问这个问题就说明你根本没有弄懂k8s，只要有docker镜像就可以在k8s上部署

**Comment by kqkdChen** [comment]
你问这个问题就说明你根本没有弄懂k8s，只要有docker镜像就可以在k8s上部署

**Comment by ATM006** [comment]
我是想问你们是否开发对应的yaml部署代码，以便修改配置，而不是默认部署。而不希望通过把配置文件映射到本地手动修改，在规模较大的情况下不是很使用。

**Comment by ATM006** [comment]
近期是否有支持k8s YAML相关内容计划？感谢！

**Comment by kqkdChen** [comment]
> 近期是否有支持k8s YAML相关内容计划？感谢！

我不是官方人员，这个建议去iotdb官方群反馈，现阶段自己用k8s部署也挺方便，单实例已经稳定运行了1个月，数据量在8000W条左右

**Comment by ATM006** [comment]
@kqkdChen 好的 感谢！

**Comment by jixuan1989** [comment]
@kqkdChen   多谢回复。
@ATM006 ATM 目前我熟悉的几位核心开发者都对k8s不是特别熟，欢迎大家一起贡献～

> 是否开发对应的yaml部署代码，以便修改配置，而不是默认部署

这个具体是指什么？ IoTDB可以通过`IOTDB_CONF=配置文件所在文件夹`环境变量来指定成你想要的配置文件。
