### ISSUE TITLE
count(xxx)无法用代码获取数量

### ISSUE THREAD

**Issue by ATM006** [apache/incubator-iotdb#1630]
SELECT count(eid) FROM root.IoTDB
![image](https://user-images.githubusercontent.com/24607498/90465420-ec315000-e141-11ea-9538-c506a612f71b.png)

**Comment by qiaojialin** [comment]
用的0.10.0发布版吗？ count 结果应该是 long 类型的，可以试试 getLong。要是方便的话可以提供一个简单的复现代码

**Comment by qiaojialin** [comment]
用 SessionDataSet 的 Iterator 遍历结果集，需要先调用 iterator 的 next 方法准备数据，才能通过 getXXX() 获取数据。即使只有一行也需要先调用 next

![image](https://user-images.githubusercontent.com/7240743/90714280-e7070900-e2d9-11ea-9183-12408ac1fd03.png)

**Comment by ATM006** [comment]
非常感谢  问题解决啦~
