### ISSUE TITLE
Logging level issue with Jetty

### ISSUE THREAD

**Issue by ope-nz** [apache/incubator-iotdb#1636]
**Describe the bug**
I have an existing project that uses Jetty. When I include the iotdb JDBC library (and dependencies) to my existing project the logging level for Jetty appears to be changed and I get additional logging occuring. This is even without initializing the iotdb JDBC library.

**To Reproduce**
1. Open an existring project that uses Jetty
2. Add iotdb JDBC library (and dependencies) 
3. Run the project
4. See additional logging occuring

**Expected behavior**
The logging behaviour shouldnt be altered

Without iotdb JDBC 

![image](https://user-images.githubusercontent.com/26259049/90711465-e891fa80-e2f4-11ea-9e6b-56970a669d47.png)

With iotdb JDBC

![image](https://user-images.githubusercontent.com/26259049/90711490-fd6e8e00-e2f4-11ea-980c-59e1708b716c.png)

**Comment by ope-nz** [comment]
Actually sorry, it appears to be the way I combined the dependencies that is causing it. Please ignore this.

**Comment by jixuan1989** [comment]
Thanks. I think the JDBC module has no dependencies related with Jetty.

**Comment by ope-nz** [comment]
I just checked and I think its something to do with slf4j or logback.

**Comment by ope-nz** [comment]
Yes, I can confirm its slf4j (from https://www.eclipse.org/jetty/documentation/current/configuring-logging.html)

**_If the class org.slf4j.Logger exists in server classpath, the Jetty implementation becomes org.eclipse.jetty.util.log.Slf4jLog._**
