### ISSUE TITLE
IoTDB是否支持ORDER排序功能

### ISSUE THREAD

**Issue by ATM006** [apache/incubator-iotdb#1640]
IoTDB是否支持ORDER排序功能，希望通过ORDER关键字查询排序输出结果

**Comment by qiaojialin** [comment]
还没有，会先加上 order by time asc/desc ，支持按时间升序和倒序。
按值排序还没有，有按值排序的需求吗？

**Comment by ATM006** [comment]
是的，希望获取到记录是时间倒叙。如果近期不能支持我就只能通过代码实现效果了。

**Comment by qiaojialin** [comment]
现在社区正在开发，快的话估计2周吧

**Comment by liutaohua** [comment]
预计下周3能有一个版本，可以稍等两天

**Comment by ATM006** [comment]
请问当前0.10.1版本支持了吗

**Comment by liutaohua** [comment]
> 请问当前0.10.1版本支持了吗

不支持，目前还没有把pr合并到master
