### ISSUE TITLE
JDBC - createCompleteSql logging (info -> debug)

### ISSUE THREAD

**Issue by ope-nz** [apache/incubator-iotdb#1645]
I am pushing data into iotdb via JDBC. The createCompleteSql function currently logs at the "info" level so every single SQL insert statement is being logged by default.

Can I please request this logging is changed to the "debug" level?

private String createCompleteSql(final String sql, Map<Integer, String> parameters)
...
      LoggerFactory.getLogger(IoTDBPreparedStatement.class).**info**("SQL {}",sql);
      LoggerFactory.getLogger(IoTDBPreparedStatement.class).**info**("parameters {}",parameters.size());
...

  }

**Comment by qiaojialin** [comment]
Sure~ Thanks for your feedback.

**Comment by qiaojialin** [comment]
You can fetch the latest master branch. Besides, I recommend using the native API (Session and SessionPool), which is more efficient.

**Comment by ope-nz** [comment]
Thanks!
