### ISSUE TITLE
Wrong tsfile_storage_fs, please set as: LOCAL ! 

### ISSUE THREAD

**Issue by Spike723** [apache/incubator-iotdb#1653]
使用的是0.10版本
配置iotdb对接HDFS的时候，启动server会提示这个问题，是配置有问题吗？为什么会提示配置成LOCAL模式？
错误日志：2020-08-26 05:13:17,537 [main] INFO  org.apache.iotdb.db.conf.IoTDBConfigCheck:93 - Starting IoTDB 0.10.0 
2020-08-26 05:13:17,539 [main] ERROR org.apache.iotdb.db.conf.IoTDBConfigCheck:277 - Wrong tsfile_storage_fs, please set as: LOCAL ! 

下面是iotdb-engine.properties有关hdfs的配置

tsfile_storage_fs=HDFS

core_site_path=/etc/hadoop/conf/core-site.xml

hdfs_site_path=/etc/hadoop/conf/hdfs-site.xml

hdfs_ip=localhost

hdfs_port=9000

麻烦了

**Comment by qiaojialin** [comment]
这个需要在第一次启动之前配置好，第一次启动之后就不能再改了，可以把 data 目录重新清一下再启动。

The tsfile_storage_fs should be set before the first start and should not be changed ever. You can remove the data dir and retry.

**Comment by samperson1997** [comment]
你好，感谢使用 HDFS 存储 tsfile 功能：）出现这个问题是由于之前本地有data file没有清空造成的。如果想使用HDFS模式，请首先清空本地的data file，然后配置才能生效。在[官方文档配置项说明](https://iotdb.apache.org/UserGuide/Master/Server/Config%20Manual.html)中，凡是提到`Only allowed to be modified in first start up`的，都仅在第一次启动时生效，重启时不能修改。
![image](https://user-images.githubusercontent.com/19167280/91248465-4f953080-e787-11ea-833c-0ab324042661.png)

Hi, thanks for using HDFS tsfile storage. Please try to clear the data file in local system as configuration document instructs: `Only allowed to be modified in first start up`.

**Comment by Spike723** [comment]
感谢 可能是在打包时候不小心把local模式下data目录的内容打进去了，所以导致解压完后，即使是第一次启动时使用hdfs也仍然报错，清空了data后没问题了。十分感谢
