### ISSUE TITLE
能不能增加更多的设计文档

### ISSUE THREAD

**Issue by liutaohua** [apache/incubator-iotdb#718]
你好，非常荣幸看到你们的项目！

我了解到目前该数据库已经拥有了非常好的性能表现，我也非常想参与其中！但是我没有找到关于iotdb详细的解释，能够让我在打开一个具体类的时候，知道我在改动整个数据库里的哪一块，并且它的上下游都分别会影响什么！

能不能增加一个清晰的类似于导航地图一样的图或文档帮助我们理解！
谢谢

**Comment by qiaojialin** [comment]
http://iotdb.apache.org/SystemDesign/0-Architecture/1-Architecture.html
