### ISSUE TITLE
元数据树里的节点如何添加属性信息

### ISSUE THREAD

**Issue by juice411** [apache/incubator-iotdb#873]
每个测点除了必要的时序数据外还有一些固定的属性数据也很重要，但是目前Iotdb无法管理属性数据。
可以针对属性进行过滤和查询，如果缺失这个功能的话，客户使用中就不得不引入第三方方案，有些不便利。比如：
![图片](https://user-images.githubusercontent.com/10968514/75750328-ec3dbf00-5d5e-11ea-8ea6-ab1dd3edc9f2.png)
![图片](https://user-images.githubusercontent.com/10968514/75750618-93baf180-5d5f-11ea-9add-de27674d8d7b.png)

图中展示的仅仅是部分属性，就是针对这些属性，如果是文本要支持模糊查询，数字的话支持比较过滤，但类似单位（比如）这种属性就不做要求。

**Comment by qiaojialin** [comment]
https://github.com/apache/incubator-iotdb/pull/1034
